// <auto-generated />
using System;
using MUNityAngular.DataHandlers.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MUNityAngular.Migrations
{
    [DbContext(typeof(MunityContext))]
    [Migration("20200717121604_RemovedUnimplementedStrcutures")]
    partial class RemovedUnimplementedStrcutures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MUNityAngular.Models.Resolution.V2.ResolutionAuth", b =>
                {
                    b.Property<string>("ResolutionId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<bool>("AllowCommitteeRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowConferenceRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPublicEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowPublicRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CommitteeId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastChangeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublicShortKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ResolutionId");

                    b.ToTable("ResolutionAuths");
                });

            modelBuilder.Entity("MUNityAngular.Models.Resolution.V2.ResolutionUser", b =>
                {
                    b.Property<int>("ResolutionUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoreUserId")
                        .HasColumnType("int");

                    b.Property<string>("ForeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ResolutionAuthResolutionId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("ResolutionAuthResolutionId1")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ResolutionUserId");

                    b.HasIndex("ResolutionAuthResolutionId");

                    b.HasIndex("ResolutionAuthResolutionId1");

                    b.ToTable("ResolutionUser");
                });

            modelBuilder.Entity("MUNityAngular.Models.Resolution.V2.ResolutionUser", b =>
                {
                    b.HasOne("MUNityAngular.Models.Resolution.V2.ResolutionAuth", null)
                        .WithMany("AllowedEditors")
                        .HasForeignKey("ResolutionAuthResolutionId");

                    b.HasOne("MUNityAngular.Models.Resolution.V2.ResolutionAuth", null)
                        .WithMany("AllowedSpectators")
                        .HasForeignKey("ResolutionAuthResolutionId1");
                });
#pragma warning restore 612, 618
        }
    }
}
