using MUNity.Base;
using MUNity.Models.Simulation;
using System;
using System.Collections.Generic;
using System.Text;

namespace MUNity.Models.Simulation
{
    /// <summary>
    /// The overall implementation of a petition.
    /// A Petition is a request that can be made by a SimulationUser and is regarding an agendaItem.
    /// The Petition is referencing a petition Type <see cref="PetitionTypeId"/> <see cref="MUNity.VirtualCommittees.Dtos.PetitionTypeDto"/>
    /// </summary>
    public interface IPetition
    {

        /// <summary>
        /// The Id of the Petition generated by the GUID when creating a new isntance.
        /// </summary>
        string PetitionId { get; set; }

        /// <summary>
        /// References a Petition Type.
        /// <see cref="MUNity.VirtualCommittees.Dtos.PetitionTypeDto"/>
        /// </summary>
        int PetitionTypeId { get; set; }

        /// <summary>
        /// The current Status of the petition.
        /// </summary>
        EPetitionStates Status { get; set; }

        /// <summary>
        /// An optional Text for the Petition.
        /// </summary>
        string Text { get; set; }

        /// <summary>
        /// The DateTime when the Petition has been created.
        /// </summary>
        DateTime PetitionDate { get; set; }

        /// <summary>
        /// The UserId of the Petition. This is the Real user Id not the PublicUserId.
        /// </summary>
        int PetitionUserId { get; set; }

        /// <summary>
        /// The AgendaItem that this petition is refering to.
        /// </summary>
        int TargetAgendaItemId { get; set; }
    }
}
