using MUNity.Base;
using MUNity.Models.Simulation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace MUNity.VirtualCommittees.Dtos
{
    /// <summary>
    /// Users inside the Simulation can make Petition that can be accepted or denied by the Leader.
    /// </summary>
    public class PetitionDto : IPetition
    {

        /// <summary>
        /// The Id of the Petition generated by the GUID when creating a new isntance.
        /// </summary>
        public string PetitionId { get; set; }

        /// <summary>
        /// References a Petition Type.
        /// </summary>
        public int PetitionTypeId { get; set; }

        public string PetitionCategoryName { get; set; }

        public string PetitionTypeName { get; set; }

        /// <summary>
        /// The current Status of the petition.
        /// </summary>
        public EPetitionStates Status { get; set; }

        /// <summary>
        /// An optional Text for the Petition.
        /// </summary>
        public string Text { get; set; }

        /// <summary>
        /// The DateTime when the Petition has been created.
        /// </summary>
        public DateTime PetitionDate { get; set; }

        /// <summary>
        /// The UserId of the Petition. This is the Real user Id not the PublicUserId.
        /// </summary>
        public int PetitionUserId { get; set; }

        public string PetitionUserIso { get; set; }

        public string PetitionUserName { get; set; }

        /// <summary>
        /// The AgendaItem that this petition is refering to.
        /// </summary>
        public int TargetAgendaItemId { get; set; }

        public int PetitionTypeSortOrder { get; set; }

        /// <summary>
        /// Creates a new Petition and generates a new Guid, Text will be string.Empty and the PetitionDate the current DateTime.
        /// </summary>
        public PetitionDto()
        {
            this.PetitionId = Guid.NewGuid().ToString();
            this.Text = "";
            this.PetitionDate = DateTime.Now;
        }
    }
}
