// <auto-generated />
using System;
using MUNityAngular.DataHandlers.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MUNityAngular.Migrations.MunCore
{
    [DbContext(typeof(MunCoreContext))]
    [Migration("20200622203727_NewCore")]
    partial class NewCore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MUNityAngular.Models.Conference.AbstractRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApplicationState")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IconName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("RoleAuthId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RoleId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("RoleAuthId");

                    b.ToTable("AbstractRole");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Committee", b =>
                {
                    b.Property<string>("CommitteeId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Article")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ResolutlyCommitteeCommitteeId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.HasKey("CommitteeId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("ResolutlyCommitteeCommitteeId");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.CommitteeTopic", b =>
                {
                    b.Property<int>("CommitteeTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommitteeId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("TopicCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TopicDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TopicFullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TopicName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CommitteeTopicId");

                    b.HasIndex("CommitteeId");

                    b.ToTable("CommitteeTopic");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Conference", b =>
                {
                    b.Property<string>("ConferenceId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConferenceProjectProjectId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreationUserUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConferenceId");

                    b.HasIndex("ConferenceProjectProjectId");

                    b.HasIndex("CreationUserUserId");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Delegation", b =>
                {
                    b.Property<string>("DelegationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DelegationId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Delegation");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.GroupApplication", b =>
                {
                    b.Property<int>("GroupApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DelegationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GroupApplicationId");

                    b.HasIndex("DelegationId");

                    b.HasIndex("RoleId");

                    b.ToTable("GroupApplications");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.GroupedRoleApplication", b =>
                {
                    b.Property<int>("GroupedRoleApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GroupedRoleApplicationId");

                    b.ToTable("GroupedRoleApplications");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Participation", b =>
                {
                    b.Property<int>("ParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<bool>("IsMainRole")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Paid")
                        .HasColumnType("double");

                    b.Property<string>("ParticipationSecret")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ParticipationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("ProjectAbbreviation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProjectName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProjectOrganisationOrganisationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectOrganisationOrganisationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.RoleApplication", b =>
                {
                    b.Property<int>("RoleApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GroupedRoleApplicationId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleApplicationId");

                    b.HasIndex("GroupedRoleApplicationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleApplications");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.RoleAuth", b =>
                {
                    b.Property<int>("RoleAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanEditConferenceSettings")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEditParticipations")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanSeeApplications")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.Property<string>("RoleAuthName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RoleAuthId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("RoleAuths");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("StateFullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StateIso")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StateName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("MUNityAngular.Models.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Forename")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GroupApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Housenumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lastname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProfileImageName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.HasIndex("GroupApplicationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MUNityAngular.Models.Core.UserAuth", b =>
                {
                    b.Property<int>("UserAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanCreateOrganisation")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAuthId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuths");
                });

            modelBuilder.Entity("MUNityAngular.Models.Organisation.Organisation", b =>
                {
                    b.Property<string>("OrganisationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("OrganisationAbbreviation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OrganisationId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("MUNityAngular.Models.Organisation.OrganisationMember", b =>
                {
                    b.Property<int>("OrganisationMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int?>("RoleOrganisationRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationMemberId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("RoleOrganisationRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganisationMember");
                });

            modelBuilder.Entity("MUNityAngular.Models.Organisation.OrganisationRole", b =>
                {
                    b.Property<int>("OrganisationRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanCreateProject")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OrganisationRoleId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OrganisationRoles");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.DelegateRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<string>("CommitteeId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<int?>("DelegateStateStateId")
                        .HasColumnType("int");

                    b.Property<string>("DelegationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDelegationLeader")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("DelegateStateStateId");

                    b.HasIndex("DelegationId");

                    b.HasDiscriminator().HasValue("DelegateRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.NgoRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<bool>("Leader")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NgoName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("NgoRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.PressRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<int>("PressCategory")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PressRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.SecretaryGeneralRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<string>("Title")
                        .HasColumnName("SecretaryGeneralRole_Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("SecretaryGeneralRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.TeamRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<int?>("ParentTeamRoleRoleId")
                        .HasColumnType("int");

                    b.Property<int>("TeamRoleGroup")
                        .HasColumnType("int");

                    b.HasIndex("ParentTeamRoleRoleId");

                    b.HasDiscriminator().HasValue("TeamRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.VisitorRole", b =>
                {
                    b.HasBaseType("MUNityAngular.Models.Conference.AbstractRole");

                    b.Property<string>("Organisation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasDiscriminator().HasValue("VisitorRole");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.AbstractRole", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");

                    b.HasOne("MUNityAngular.Models.Conference.RoleAuth", "RoleAuth")
                        .WithMany()
                        .HasForeignKey("RoleAuthId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Committee", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Conference", "Conference")
                        .WithMany("Committees")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MUNityAngular.Models.Conference.Committee", "ResolutlyCommittee")
                        .WithMany()
                        .HasForeignKey("ResolutlyCommitteeCommitteeId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.CommitteeTopic", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Committee", null)
                        .WithMany("Topics")
                        .HasForeignKey("CommitteeId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Conference", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Project", "ConferenceProject")
                        .WithMany("Conferences")
                        .HasForeignKey("ConferenceProjectProjectId");

                    b.HasOne("MUNityAngular.Models.Core.User", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserUserId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Delegation", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.GroupApplication", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Delegation", "Delegation")
                        .WithMany()
                        .HasForeignKey("DelegationId");

                    b.HasOne("MUNityAngular.Models.Conference.AbstractRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Participation", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.AbstractRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("MUNityAngular.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Project", b =>
                {
                    b.HasOne("MUNityAngular.Models.Organisation.Organisation", "ProjectOrganisation")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectOrganisationOrganisationId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.RoleApplication", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.GroupedRoleApplication", null)
                        .WithMany("Applications")
                        .HasForeignKey("GroupedRoleApplicationId");

                    b.HasOne("MUNityAngular.Models.Conference.AbstractRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("MUNityAngular.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.RoleAuth", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Core.User", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.GroupApplication", null)
                        .WithMany("Users")
                        .HasForeignKey("GroupApplicationId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Core.UserAuth", b =>
                {
                    b.HasOne("MUNityAngular.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Organisation.OrganisationMember", b =>
                {
                    b.HasOne("MUNityAngular.Models.Organisation.Organisation", "Organisation")
                        .WithMany("Member")
                        .HasForeignKey("OrganisationId");

                    b.HasOne("MUNityAngular.Models.Organisation.OrganisationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleOrganisationRoleId");

                    b.HasOne("MUNityAngular.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Organisation.OrganisationRole", b =>
                {
                    b.HasOne("MUNityAngular.Models.Organisation.Organisation", "Organisation")
                        .WithMany("Roles")
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.DelegateRole", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Committee", "Committee")
                        .WithMany()
                        .HasForeignKey("CommitteeId");

                    b.HasOne("MUNityAngular.Models.Conference.State", "DelegateState")
                        .WithMany()
                        .HasForeignKey("DelegateStateStateId");

                    b.HasOne("MUNityAngular.Models.Conference.Delegation", "Delegation")
                        .WithMany()
                        .HasForeignKey("DelegationId");
                });

            modelBuilder.Entity("MUNityAngular.Models.Conference.Roles.TeamRole", b =>
                {
                    b.HasOne("MUNityAngular.Models.Conference.Roles.TeamRole", "ParentTeamRole")
                        .WithMany()
                        .HasForeignKey("ParentTeamRoleRoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
