using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;
using System.Text;

namespace MUNity.Models.Resolution
{

    /// <summary>
    /// A resolution is a type of document to work with inside a committee. The Resolution contains the three parts:
    /// Header, Preamble, OperativeSection.
    /// The Header is containing the general information of the document like name, submitter, topic etc.
    /// The Preamble contains a list of paragraphs.
    /// The operative section contains a list of paragraphs and amendments for the different paragraphs that are created.
    /// </summary>
    public class Resolution
    {

        /// <summary>
        /// An id to let the system identify the resolution. Note that the header contains a property for name or full name
        /// if you want to have another solution for your users to find the resolution easier. The Id is generated by the
        /// Resolution itself when it is created.
        /// </summary>
        [Key]
        public string ResolutionId { get; set; }


        /// <summary>
        /// A Date that is first set when the resolution is created and can be used as a last change date.
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// The header of the resolution containing the general information of the document.
        /// </summary>
        public ResolutionHeader Header { get; set; }

        /// <summary>
        /// The preamble of the resolution containing the different paragraphs.
        /// </summary>
        public ResolutionPreamble Preamble { get; set; }

        /// <summary>
        /// The operative section of the resolution containing the paragraphs and amendments.
        /// </summary>
        public OperativeSection OperativeSection { get; set; }

        /// <summary>
        /// Creates a new instance of a resolution with a new Id.
        /// </summary>
        public Resolution()
        {
            ResolutionId = Guid.NewGuid().ToString();
            Preamble = new ResolutionPreamble();
            OperativeSection = new OperativeSection();
            Header = new ResolutionHeader();
            Date = DateTime.Now;
        }
    }
}
