// <auto-generated />
using MUNityAngular.DataHandlers.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MUNityAngular.Migrations.Conference
{
    [DbContext(typeof(ConferenceContext))]
    [Migration("20200604133810_NewConferenceStructureInit")]
    partial class NewConferenceStructureInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MUNityAngular.Models.Organisations.Organisations", b =>
                {
                    b.Property<string>("OrganisationId")
                        .HasColumnType("varchar(95) CHARACTER SET utf8mb4");

                    b.Property<string>("OrganisationAbbreviation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OrganisationId");

                    b.ToTable("Organisations");
                });
#pragma warning restore 612, 618
        }
    }
}
